backend:
  name: github
  branch: main
  repo: inclusive-design/responsible-ai
  base_url: https://auth.incd.ca
  commit_messages:
    create: 'chore(cms): create "{{path}}"'
    update: 'chore(cms): update "{{path}}"'
    delete: 'chore(cms): delete "{{path}}"'
    uploadMedia: 'chore(cms): upload "{{path}}"'
    deleteMedia: 'chore(cms): delete "{{path}}"'
media_folder: src/assets/uploads
public_folder: /assets/uploads
app_title: Responsible AI

i18n:
  locales: [en, fr]
  default_locale: en
  initial_locales: default
field_defaults:
  richtext:
    minimal: true
    buttons: [bold, italic, link]
    editor_components: []

collections:
  - label: Pages
    label_singular: Page
    name: pages
    icon: article
    thumbnail: false
    i18n:
      structure: multiple_folders
    folder: src/collections/pages/
    extension: md
    slug: "{{fields._slug | localize}}"
    view_filters:
      - label: Drafts
        field: draft
        pattern: true
    sortable_fields:
      fields: [title, order]
      default:
          field: order
          direction: ascending
    fields:
      - label: Title
        name: title
        widget: string
        i18n: true
      - label: Short Title
        name: shortTitle
        widget: string
        i18n: true
        required: false
      - label: Draft
        name: draft
        widget: boolean
        i18n: duplicate
        required: false
      - label: Language
        name: lang
        widget: hidden
        default: "{{locale}}"
      - label: Navigation Order
        name: order
        widget: number
        i18n: duplicate
        required: false
      - label: Parent
        name: parent
        widget: relation
        i18n: true
        collection: pages
        value_field: translationKey
        search_fields: [title]
        display_fields: [title]
        multiple: false
        required: false
      - label: Layout
        name: layout
        widget: hidden
        i18n: duplicate
        default: layouts/base
        required: true
      - label: Excerpt
        name: excerpt
        widget: text
        i18n: true
        required: false
      # - label: Preview Image
      #   name: previewImage
      #   widget: image
      #   i18n: duplicate
      #   required: false
      #   hint: This image should be 1200 by 630 pixels and will be used as a preview image when this page is shared on social media.
      # - label: Preview Image Alt Text
      #   name: previewImageAlt
      #   widget: string
      #   i18n: true
      #   required: false
      # - label: Banner Title
      #   name: bannerTitle
      #   widget: text
      #   i18n: true
      #   required: false
      - label: Banner Text
        name: bannerText
        widget: text
        i18n: true
        required: false
      # - label: Banner Image
      #   name: bannerImage
      #   widget: image
      #   i18n: duplicate
      #   required: false
      # - label: Banner Image Alt Text
      #   name: bannerImageAlt
      #   widget: text
      #   i18n: true
      #   required: false
      - label: Body
        name: body
        widget: markdown
        i18n: true
        buttons: [bold, italic, link, heading-two, heading-three]
      # - label: Outro
      #   name: outro
      #   widget: markdown
      #   i18n: true
      #   buttons: [bold, italic, link, heading-two, heading-three]
      #   required: false
  - label: Opportunities
    label_singular: Opportunity
    name: opportunities
    i18n:
      structure: multiple_folders
    folder: src/collections/opportunities/
    icon: check_circle
    slug: "{{index}}"
    summary: '{{index}}. {{title}}'
    fields:
      - label: Index
        name: index
        widget: string
        i18n: duplicate
      - label: Title
        name: title
        widget: string
        i18n: true
      - label: Excerpt
        name: excerpt
        widget: text
        i18n: true
      - label: Opportunity
        name: opportunity
        widget: markdown
        i18n: true
      - label: Limitation
        name: limitation
        widget: markdown
        i18n: true
      - label: Illustrative Examples
        label_singular: Example
        name: examples
        widget: list
        required: false
        i18n: true
        fields:
          - label: Title
            name: title
            widget: string
            i18n: true
          - label: Example
            name: example
            widget: markdown
            i18n: true
          - label: Caution
            name: caution
            widget: markdown
            i18n: true
  - label: Risks
    label_singular: Risk
    name: risks
    i18n:
      structure: multiple_folders
    folder: src/collections/risks/
    icon: warning
    slug: "{{index}}"
    summary: '{{index}}. {{title}}'
    fields:
      - label: Index
        name: index
        widget: string
        i18n: duplicate
      - label: Title
        name: title
        widget: string
        i18n: true
      - label: Excerpt
        name: excerpt
        widget: text
        i18n: true
      - label: Risk
        name: risk
        widget: markdown
        required: true
        i18n: true
      - label: Mitigation
        name: mitigation
        widget: markdown
        required: true
        i18n: true
      - label: Illustrative Examples
        name: examples
        widget: object
        required: false
        i18n: true
        fields:
          - label: Education
            label_singular: Education Example
            name: education
            widget: list
            i18n: true
            required: false
            field:
              label: Education Example
              name: example
              widget: markdown
              i18n: true
          - label: Employment
            label_singular: Employment Example
            name: employment
            widget: list
            i18n: true
            required: false
            field:
              label: Employment Example
              name: example
              widget: markdown
              i18n: true
          - label: Healthcare
            label_singular: Healthcare Example
            name: healthcare
            widget: list
            i18n: true
            required: false
            field:
              label: Healthcare Example
              name: example
              widget: markdown
              i18n: true
          - label: Services
            label_singular: Services Example
            name: services
            widget: list
            i18n: true
            required: false
            field:
              label: Services Example
              name: example
              widget: markdown
              i18n: true
